=== hetalang/heta-compiler/src/builder/declaration-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/hetalang/heta-compiler/master/src/builder/declaration-schema.json",
  "title": "Heta platform declaration",
  "description": "Describes platform.json file in Heta compiler.",
  "type": "object",
  "required": ["options", "importModule", "export"],
  "additionalProperties": true,
  "properties": {
    "$schema": {"type": "string"},
    "id": {"type": "string"},
    "notes": {"type": "string"},
    "version": {"type": "string"},
    "keywords": {"type": "array", "items": {"type": "string"}},
    "homepage": {"type": "string"},
    "repository": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "type": {"type": "string"},
        "url": {"type": "string"}
      }
    },
    "license": {"type": "string", "default": "UNLICENSED", "description": "see https://spdx.org/licenses/"},
    "private": {"type": "boolean"},
    "contributors": {"type": "array", "items": {"type": "string", "example": "Your Name <email@example.com> (http://example.com)"}},
    "builderVersion": {"type": "string", "default": "*"},
    "options": {
      "type": "object",
      "additionalProperties": {
        "not": true,
        "errorMessage": "${0#} is unknown key in options"
      },
      "properties": {
        "unitsCheck": {"type": "boolean", "default": false},
        "distDir": {"type": "string", "default": "dist" },
        "debug": {"type": "boolean", "default": false, "description": "Should we put parsed modules to meta?"},
        "metaDir": {"type": "string", "default": "meta" }
      },
      "default": {"debug": false}
    },
    "scripts": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "afterInit": {"type": "string"},
        "afterImports": {"type": "string"},
        "afterExports": {"type": "string"}
      }
    },
    "importModule": {
      "type": "object",
      "default": {"type": "heta", "source": "index.heta"},
      "additionalProperties": true,
      "properties": {
        "type": {"type": "string", "enum": ["heta", "table", "xlsx", "json", "yaml", "sbml"], "default": "heta"},
        "source": {"type": "string", "default": "index.heta"},
        "sheet": {"type": "integer"},
        "omitRows": {"type": "integer", "minimum": 0},
        "transpose": {"type": "boolean", "default": false}
      }
    },
    "export": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "required": ["format"],
        "additionalProperties": true,
        "properties": {
          "id": {"type": "string"},
          "format": {"type": "string"},
          "filepath": {"type": "string"},
          "spaceFilter": {"type": "string"}
        }
      }
    }
  }
}

=== hetalang/heta-compiler/cases/20-syntax/platform.json
{
  "builderVersion": "*",
  "id": "template",
  "notes": "platform notes",
  "version": "v0.1.0",
  "license": "UNLICENSED",
  "options": {
    "debug": false,
    "unitsCheck": false
  },
  "importModule": {
    "type": "heta",
    "source": "src/index.heta"
  },
  "export": [
    {
      "format": "JSON"
    },
    {
      "format": "YAML"
    },
    {
      "format": "XLSX",
      "omitRows": 3,
      "splitByClass": true
    },
    {
      "format": "SBML",
      "version": "L2V4"
    },
    {
      "format": "SLV",
      "eventsOff": false
    },
    {
      "format": "DBSolve"
    },
    {
      "format": "Simbio"
    },
    {
      "format": "Mrgsolve"
    },
    {
      "format": "Julia"
    },
    {
      "format": "Matlab"
    }
  ]
}

=== hetalang/heta-compiler/cases/19-time-scale/platform.json
{
  "builderVersion": "*",
  "id": "template",
  "notes": "platform notes",
  "version": "v0.1.0",
  "license": "UNLICENSED",
  "options": {
    "unitsCheck": true
  },
  "importModule": {
    "type": "heta",
    "source": "src/index.heta"
  },
  "export": [
    {
      "format": "JSON"
    },
    {
      "format": "YAML"
    },
    {
      "format": "XLSX",
      "omitRows": 3,
      "splitByClass": true
    },
    {
      "format": "SBML",
      "version": "L2V4",
      "spaceFilter": "zzz"
    },
    {
      "format": "SLV",
      "spaceFilter": "zzz"
    },
    {
      "format": "DBSolve",
      "spaceFilter": "zzz"
    },
    {
      "format": "Simbio",
      "spaceFilter": "zzz"
    },
    {
      "format": "Mrgsolve",
      "spaceFilter": "zzz"
    },
    {
      "format": "Matlab",
      "spaceFilter": "zzz"
    },
    {
      "format": "Julia",
      "spaceFilter": "zzz"
    }
  ]
}

=== hetalang/heta-compiler/cases/15-switcher-variants/platform.json
{
  "builderVersion": "*",
  "id": "template",
  "notes": "platform notes",
  "version": "v0.1.0",
  "license": "UNLICENSED",
  "options": {
    "unitsCheck": false
  },
  "importModule": {
    "type": "heta",
    "source": "src/index.heta"
  },
  "export": [
    {
      "format": "Julia"
    }
  ]
}

=== hetalang/heta-compiler/cases/25-units-check/platform.json
{
  "builderVersion": "*",
  "id": "template",
  "notes": "platform notes",
  "version": "v0.1.0",
  "license": "UNLICENSED",
  "options": {
    "unitsCheck": true
  },
  "importModule": {
    "type": "heta",
    "source": "src/index.heta"
  },
  "export": [
    {
      "format": "JSON"
    }
  ]
}

=== hetalang/heta-compiler/cases/21-scenario/platform.json
{
  "builderVersion": "*",
  "id": "template",
  "notes": "platform notes",
  "version": "v0.1.0",
  "license": "UNLICENSED",
  "options": {},
  "importModule": {
    "type": "heta",
    "source": "src/index.heta"
  },
  "export": [
    {
      "format": "JSON"
    },
    {
      "format": "YAML"
    },
    {
      "format": "XLSX",
      "omitRows": 3,
      "splitByClass": true
    },
    {
      "format": "Julia"
    }
  ]
}

=== hetalang/heta-compiler/cases/24-define-function/platform.json
{
  "builderVersion": "*",
  "id": "template",
  "notes": "platform notes",
  "version": "v0.1.0",
  "license": "UNLICENSED",
  "options": {},
  "importModule": {
    "type": "heta",
    "source": "src/index.heta"
  },
  "export": [
    {
      "format": "JSON"
    },
    {
      "format": "YAML"
    },
    {
      "format": "Table",
      "omitRows": 3,
      "splitByClass": true
    },
    {
      "format": "XLSX",
      "omitRows": 3,
      "splitByClass": true
    },
    {
      "format": "SBML",
      "version": "L2V4"
    },
    {
      "format": "DBSolve"
    },
    {
      "format": "SLV"
    },
    {
      "format": "HetaCode"
    },
    {
      "format": "Simbio"
    },
    {
      "format": "Mrgsolve"
    },
    {
      "format": "Matlab"
    },
    {
      "format": "Julia"
    }
  ]
}

=== hetalang/heta-compiler/cases/17-multispace/platform.json
{
  "builderVersion": "*",
  "id": "template",
  "options": {
    "debug": false
  },
  "importModule": {
    "type": "heta",
    "source": "src/index.heta"
  },
  "export": [
    {
      "format": "JSON",
      "spaceFilter": "(nameless)|(one)|(two)",
      "useUnitsExpr": false
    },
    {
      "format": "YAML",
      "spaceFilter": "one",
      "useUnitsExpr": false
    },
    {
      "format": "XLSX",
      "omitRows": 3,
      "splitByClass": true,
      "spaceFilter": "one"
    },
    {
      "format": "HetaCode",
      "spaceFilter": "(one)|(two)"
    },
    {
      "format": "SBML",
      "version": "L2V4",
      "spaceFilter": "(one)|(two)"
    },
    {
      "format": "Simbio"
    },
    {
      "format": "Mrgsolve",
      "spaceFilter": "(nameless)|(one)"
    },
    {
      "format": "SLV",
      "eventsOff": false,
      "spaceFilter": "one"
    },
    {
      "format": "DBSolve",
      "eventsOff": false,
      "spaceFilter": "one"
    },
    {
      "format": "Matlab",
      "spaceFilter": "(nameless)|(one)"
    },
    {
      "format": "Julia",
      "spaceFilter": "nameless"
    }
  ]
}
